import type { RoadmapStep } from '@/types';

export const roadmapSteps: RoadmapStep[] = [
  {
    id: 1,
    title: 'Introduction to Docker',
    description:
      'Docker is a platform for developing, shipping, and running applications inside lightweight containers. Containers package code and dependencies together, ensuring consistency across environments.',
    practice: 'Understand what containers are and how they differ from traditional virtualization.',
    commands: ['docker --version', 'docker version', 'docker info'],
  },
  {
    id: 2,
    title: 'Virtual Machines vs Containers',
    description:
      'VMs virtualize hardware and run a full OS, while containers share the host OS kernel. Containers are lighter, faster, and more resource-efficient than virtual machines.',
    practice: 'Study the architectural differences between VMs and containers.',
    commands: [],
  },
  {
    id: 3,
    title: 'Installing Docker',
    description:
      'Docker can be installed on Windows, macOS, and Linux. Docker Desktop provides a GUI, while Docker Engine can be installed via CLI on Linux servers.',
    practice: 'Install Docker on your machine and verify the installation.',
    commands: ['docker run hello-world', 'docker --version', 'which docker'],
  },
  {
    id: 4,
    title: 'Docker Images',
    description:
      'An image is a read-only template with instructions for creating a container. Images are built from a Dockerfile and stored in registries like Docker Hub.',
    practice: 'Pull images from Docker Hub and list them locally.',
    commands: ['docker images', 'docker pull nginx', 'docker rmi nginx', 'docker build -t my-app .'],
  },
  {
    id: 5,
    title: 'Docker Containers',
    description:
      'A container is a runnable instance of an image. Containers can be started, stopped, moved, and deleted. Each container runs isolated from others.',
    practice: 'Run, stop, and manage containers. Practice port mapping and detached mode.',
    commands: [
      'docker run hello-world',
      'docker run -d -p 8080:80 nginx',
      'docker ps',
      'docker ps -a',
      'docker stop container_id',
      'docker rm container_id',
    ],
  },
  {
    id: 6,
    title: 'Docker Hub',
    description:
      'Docker Hub is a public registry for Docker images. You can pull official images and push your own custom images to share with the community.',
    practice: 'Create a Docker Hub account, pull images, and try pushing an image.',
    commands: ['docker login', 'docker push username/my-app', 'docker pull node:20-alpine'],
  },
  {
    id: 7,
    title: 'Dockerfile',
    description:
      'A Dockerfile is a text file with instructions to build a Docker image. It defines the base image, dependencies, configuration, and startup command.',
    practice: 'Write a Dockerfile for a simple Node.js application.',
    commands: [
      'FROM node:20-alpine',
      'WORKDIR /app',
      'COPY package*.json ./',
      'RUN npm install',
      'COPY . .',
      'EXPOSE 3000',
      'CMD ["npm", "start"]',
    ],
  },
  {
    id: 8,
    title: 'Volumes',
    description:
      'Volumes persist data generated by containers. They survive container restarts and removals, making them essential for databases and stateful applications.',
    practice: 'Create and mount volumes to share data between containers and the host.',
    commands: [
      'docker volume ls',
      'docker volume create my-volume',
      'docker volume inspect my-volume',
      'docker run -v my-volume:/app/data nginx',
    ],
  },
  {
    id: 9,
    title: 'Networks',
    description:
      'Docker networks allow containers to communicate securely. You can create isolated networks for different application tiers.',
    practice: 'Create custom networks and connect multiple containers.',
    commands: [
      'docker network ls',
      'docker network create my-network',
      'docker network inspect my-network',
      'docker run --network my-network nginx',
    ],
  },
  {
    id: 10,
    title: 'Docker Compose',
    description:
      'Docker Compose lets you define and run multi-container applications using a YAML file. It simplifies orchestrating services, networks, and volumes.',
    practice: 'Create a docker-compose.yml for a full-stack app with Node.js and MongoDB.',
    commands: [
      'docker compose up',
      'docker compose up -d',
      'docker compose down',
      'docker compose logs',
      'docker compose ps',
    ],
  },
  {
    id: 11,
    title: 'Environment Variables',
    description:
      'Environment variables let you configure containers at runtime. They keep sensitive data out of images and make apps portable across environments.',
    practice: 'Pass environment variables to containers and use .env files.',
    commands: [
      'docker run -e NODE_ENV=production nginx',
      'docker run --env-file .env nginx',
      'docker compose config',
    ],
  },
  {
    id: 12,
    title: 'Debugging Containers',
    description:
      'Debugging containers involves inspecting logs, executing commands inside running containers, and using diagnostic tools to troubleshoot issues.',
    practice: 'Practice viewing logs and entering containers for debugging.',
    commands: [
      'docker logs container_id',
      'docker logs -f container_id',
      'docker exec -it container_id sh',
      'docker inspect container_id',
    ],
  },
  {
    id: 13,
    title: 'Cleaning Docker Resources',
    description:
      'Unused containers, images, volumes, and networks consume disk space. Docker provides prune commands to clean them safely.',
    practice: 'Clean up unused resources and understand what each prune command removes.',
    commands: [
      'docker container prune',
      'docker image prune',
      'docker volume prune',
      'docker network prune',
      'docker system prune',
      'docker system prune -a',
    ],
  },
  {
    id: 14,
    title: 'Best Practices',
    description:
      'Follow Docker best practices: use small base images, layer caching, multi-stage builds, least-privilege users, and proper tagging.',
    practice: 'Optimize a Dockerfile using multi-stage builds and Alpine images.',
    commands: [],
  },
  {
    id: 15,
    title: 'Deployment Workflow',
    description:
      'Deploy Docker containers to production using orchestration tools, CI/CD pipelines, and cloud platforms. This course site itself can be deployed via Docker.',
    practice: 'Set up a CI/CD pipeline to build and deploy Docker images.',
    commands: [],
  },
];
